package com.mthien.yumble.entity.Enum;

public enum Meal {
    BREAKFAST,
    LUNCH,
    DINNER,
    SNACK,
    ALL_TIME,
    BREAKFAST_LUNCH,
    LUNCH_DINNER,
    BREAKFAST_LUNCH_DINNER,
    DESSERT,
    APPETIZER_SNACK,
    APPETIZER_LUNCH,
    APPETIZER_DINNER,
    APPETIZER,
    SNACK_DESSERT,
    SNACK_BREAKFAST,
    SNACK_DINNER,
    SNACK_APPETIZER,
    SNACK_LUNCH
}
